export const userData = [
  {
    id: "1",
    name:"Name",
    email:"name@domain.com",
    role:"Super Admin",
  },
  {
    id: "2",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "3",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "4",
    name:"Name",
    email:"name@domain.com",
    role:"Super Admin",
  },
  {
    id: "5",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "6",
    name:"Name",
    email:"name@domain.com",
    role:"Super Admin",
  },
  {
    id: "7",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "8",
    name:"Name",
    email:"name@domain.com",
    role:"Super Admin",
  },
  {
    id: "9",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "10",
    name:"Name",
    email:"name@domain.com",
    role:"Super Admin",
  },
  {
    id: "11",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "12",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "13",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "14",
    name:"Name",
    email:"name@domain.com",
    role:"Super Admin",
  },
  {
    id: "15",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "16",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "17",
    name:"Name",
    email:"name@domain.com",
    role:"Super Admin",
  },
  {
    id: "18",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "19",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "20",
    name:"Name",
    email:"name@domain.com",
    role:"Super Admin",
  },
  {
    id: "21",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "22",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "23",
    name:"Name",
    email:"name@domain.com",
    role:"Super Admin",
  },
  {
    id: "24",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "25",
    name:"Name",
    email:"name@domain.com",
    role:"Super Admin",
  },
  {
    id: "26",
    name:"Name",
    email:"name@domain.com",
    role:"Super Admin",
  },
  {
    id: "27",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
  {
    id: "28",
    name:"Name",
    email:"name@domain.com",
    role:"Admin",
  },
];